[build]
  # Dossier de publication
  publish = "."

[build.environment]
  # Variables d'environnement si nécessaire

[[headers]]
  # Headers de sécurité
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[form]
  # Configuration des formulaires Netlify
  honeypot = "bot-field"
